### ISSUE TITLE
How to properly append domain to EasyEngine nginx?

### ISSUE THREAD

**Issue by justnorris** [EasyEngine/easyengine#761] opened 2016-09-07 11:09 UTC
`ee site create jolly.foobar.com` creates the site. 

But `jolly.foobar.com` was called `happy.barbar.org` a long time ago, so I'd like to set the server config to something like this:

`/etc/nginx/sites-available/jolly.foobar.com` contents:

```
server {
    server_name jolly.foobar.com happy.barbar.org;
  }
```

However, when I run any EasyEngine command on `jolly.foobar.com` ( like `ee site update jolly.foobar.com --php7` ), `happy.barbar.org` is automatically removed. 

How to future proof `server_name` alterations ?

**Comment by iam404** [comment] 2016-09-09 10:19
That would require alteration of `sitename` stored at `/var/lib/ee/ee.db`.

I am labeling it as feature request to `ee site rename` command.

**Comment by justnorris** [comment] 2016-09-10 10:15
@iam404 It's not really a `rename`, this could be useful for people who need multiple aliases for a single site too. For example, something like `ee site attach color.com colour.com`

**Comment by justnorris** [comment] 2016-09-10 10:20
I modified the script from [rtcamp community](http://community.rtcamp.com/t/how-to-change-domain-with-existing-ee-setup/1848/15) and works beautifully for renaming. It's the addition of the old domain that needs attention.

~~~
#!/bin/bash
 
if [ $UID -ne 0 ]; then
    echo "$0 must be run as root"
    exit 1
fi
 
if [ $# -ne 2 ]; then
  echo "Syntax: $0 [from_sitename] [to_sitename]"
  ee site list
  exit 1
fi
 
old_name=$1;
new_name=$2;
 
eedb="/var/lib/ee/ee.db"
webroot="/var/www"
nginx_dir="/etc/nginx/sites-available"
 
# this removes the symbolic link in nginx sites-enabled
ee site disable $old_name
# rename
echo "Rename.."
mv -v $webroot/$old_name $webroot/$new_name
# rename nginx config filename
mv -v $nginx_dir/$old_name $nginx_dir/$new_name
# replace from_sitename by to_sitename
 
cmd="sed -i s/$old_name/$new_name/g $nginx_dir/$new_name"
echo $cmd
$cmd
 
sql="UPDATE sites SET sitename='$new_name', site_path='$webroot/$new_name' WHERE sitename='$old_name'"
#echo sqlite3 $eedb "$sql"
sqlite3 $eedb "$sql"
 
# creates symbolic link in nginx sites-enabled
ee site enable $new_name
 
# show db-settings from ee
ee site info $new_name

# Search/replace old url to the new url with WP-CLI
sudo -u NOT_ROOT_USER wp search-replace $old_name $new_name --recurse-objects --skip-columns=guid --path=$webroot/$new_name/htdocs

~~~

**Comment by kirtangajjar** [comment] 2018-11-23 13:02
This issue is duplicate of #1033. Closing it.

**Closed by kirtangajjar** 2018-11-23 13:02 UTC
Labels: kind/feature

**Comment by justnorris** [comment] 2018-11-23 13:42
Technically, #1033 is the duplicate 😆 	- no worries - glad to see it's moving 👍

**Comment by csaltos** [comment] 2019-08-24 21:39
I solved this by simply following the instructions at the custom nginx-proxy override configurations -> https://github.com/jwilder/nginx-proxy#custom-nginx-configuration

As a summary, simply create this file:

/opt/easyengine/services/nginx-proxy/vhost.d/jolly.foobar.com

With the content:

server_name jolly.foobar.com happy.barbar.org;

Then:

ee service restart nging-proxy

And you are good to go !! ;) :)

Your changes are going to persist any other restart or reload.

NOTE: the name of the vhost file should be the same as the ee site you want to override.
