### ISSUE TITLE
-bash: lsb_release: command not found

### ISSUE THREAD

**Issue by jult** [EasyEngine/easyengine#692] opened 2016-03-30 10:28 UTC
In a plain debian wheezy it doesn't install using apt-get install lsb-release.
So you should also mention that if you use it..

**Comment by iam404** [comment] 2016-04-13 12:28
We already had that in our install script.
https://github.com/EasyEngine/easyengine/blob/master/install#L43

There may be other reason why it failed to install. As we cannot reproduce the issue in our testing server, I am closing this issue for now.

**Closed by iam404** 2016-04-13 12:28 UTC
