### ISSUE TITLE
Databases not dropping properly - weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by brennentsmith** [EasyEngine/easyengine#521] opened 2015-04-29 19:13 UTC
It appears that in the Database Drop of a Site Delete process, the code is using a weakly referenced MySQL object that the GC destroys before the operation is completed. The user and additional database are usually not dropped in this circumstance. See: 

``` bash
Executing ee site delete devtest2.wildwingstudios.com --no-prompt
Deleting Database, devtesv1wa29GVCL, user devtesO3MpaVJ1AC
Database devtesO3MpaVJ1AC not dropped
Deleted Database successfully.
Deleting Webroot, /var/www/devtest2.wildwingstudios.com
Deleted webroot successfully
Reload : nginx     [OK]
Deleted site devtest2.wildwingstudios.com

Errors
Exception ignored in: <bound method Cursor.__del__ of <pymysql.cursors.Cursor object at 0x7ff853c4d2e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/PyMySQL3-0.4-py3.4.egg/pymysql/cursors.py", line 41, in __del__
  File "/usr/local/lib/python3.4/dist-packages/PyMySQL3-0.4-py3.4.egg/pymysql/cursors.py", line 47, in close
ReferenceError: weakly-referenced object no longer exists

Executing sudo service nginx reload
 * Reloading nginx configuration nginx
   ...done.
```

**Comment by timworx** [comment] 2015-05-05 07:32
I'm hitting this same error on site creation - although not so consistently. I updated the PyMySQL package and it now seems to be OK, unless I run it from Pexpect - which is the primary way I run it.

**Comment by dethmix** [comment] 2015-08-14 16:07
Hi, I have got absolutely the same error message while using remote mysql server. Below is full error message:
ee site delete test2.com
Are you sure, you want to delete database [y/N]: y
Deleting Database, test2_com, user test2_com
Database test2_com not dropped
Exception ignored in: <bound method Cursor.__del__ of <pymysql.cursors.Cursor object at 0x7f985b68c2b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/PyMySQL3-0.4-py3.4.egg/pymysql/cursors.py", line 41, in __del__
  File "/usr/local/lib/python3.4/dist-packages/PyMySQL3-0.4-py3.4.egg/pymysql/cursors.py", line 47, in close
ReferenceError: weakly-referenced object no longer exists
Deleted Database successfully.
Are you sure, you want to delete webroot [y/N]: y
Deleting Webroot, /var/www/test2.com
Deleted webroot successfully
Reload : nginx     [OK]
Deleted site test2.com

In same time I can't reproduce it while using local mysql server. Is there any know solutions for this? EE does remove mysql database from the remote mysql server, but doesn't remove mysql user.

**Comment by rahul286** [comment] 2018-05-29 11:55
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

**Closed by rahul286** 2018-05-29 11:55 UTC
