### ISSUE TITLE
PHP Mobile detection scrips can't work with full page redis caching (Solved, could this be added to core?)

### ISSUE THREAD

**Issue by rsmith4321** [EasyEngine/easyengine#788] opened 2016-10-20 21:37 UTC
I have a photo gallery that requires a php mobile detection script to format the gallery differently for touch devices. At the moment full page redis cache breaks any mobile detection scrips because it caches the page based on the device that hit it last.  I need a way to cache mobile devices separately from desktop browsers perhaps by using useragent list.  I know this can be done with w3tc, is there any possible way to implement this with redis caching?

Please attach the output of following command when open a new support request.
- [No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 16.04.1 LTS
  Release:    16.04
  Codename:   xenial] lsb_release -a
- [ EasyEngine v3.7.4
  Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.] ee -v
- [NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.26-2):

user  
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.18-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             9
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf ] ee info
- [PHP binary:  /usr/bin/php7.0
  PHP version:    7.0.11-2+deb.sury.org~xenial+1
  php.ini used:   /etc/php/7.0/cli/php.ini
  WP-CLI root dir:    phar://wp-cli.phar
  WP-CLI packages dir:  
  WP-CLI global config:  
  WP-CLI project config:  
  WP-CLI version: 0.24.1 ] wp --allow-root --info

**Comment by lutfuahmet** [comment] 2016-10-20 22:02
I was looking for this situation. 

1 - Add this config to http block at nginx.conf file

map $http_user_agent $ua_mobile {
                default 'no';
               ~(iPhone|Android) 'yes';
}

2 - Add $ua_mobile variable to config at redis.conf file which located /etc/nginx/common

  set $key "nginx-cache:$scheme$request_method$host$request_uri**$ua_mobile**";

you can also add optional header for debugging.

add_header mobile $ua_mobile;

**Comment by MiteshShah** [comment] 2016-10-21 08:58
I'd setup same stuff for NGINX FastCGI - https://miteshshah.github.io/linux/nginx/how-to-setup-separate-nginx-fastcgi-cache-for-mobile-and-desktop-users/

**Comment by rsmith4321** [comment] 2016-10-21 19:21
Sadly lutfuahmet solution does not seem to be working.  I've got the header working for troubleshooting and it does detect mobile vs not, but it's still serves up the same cached page for both.  Are you sure your solution works for redis full page caching?  Not just the redis object cache.

**Comment by rsmith4321** [comment] 2016-10-21 19:35
Yeah, lutfuahmet solution is working!  I forgot I'm using php7 so I had to edit the redis-php7.conf file instead.  After I figured that out it seems to work!  I think this should be part of the easyengine setup a lot of plugins use mobile detection keeping a separate cache doesn't seem like a big deal.  Thanks again!

**Comment by rsmith4321** [comment] 2016-10-22 15:16
Would it be possible for this fix to be implemented in the core of easyengine?  It would just be a couple of lines of code and would probably solve issues for a lot of users.

**Comment by ddelaey** [comment] 2016-10-22 16:24
+1

**Comment by rahul286** [comment] 2018-05-29 08:51
@rsmith4321 while it is possible to add such codes in the core, we recommend using responsive design rather than doing mobile detection.

The biggest challenge with this kind of nginx config is to purge cache correctly for all variant when a page is modified. We needed to modify nginx-helper for a client. Case study https://rtcamp.com/work/vanguard-ngr/

In EE v4, we plan to cut down the number of caching option we support. Maybe once we do that we can revisit the topic.

**Comment by rahul286** [comment] 2018-08-03 13:30
Dupe of https://github.com/EasyEngine/easyengine/issues/424

**Closed by rahul286** 2018-08-03 13:30 UTC

**Comment by ggloveswp** [comment] 2019-04-24 14:51
> @rsmith4321 while it is possible to add such codes in the core, we recommend using responsive design rather than doing mobile detection.
> 
> The biggest challenge with this kind of nginx config is to purge cache correctly for all variant when a page is modified. We needed to modify nginx-helper for a client. Case study https://rtcamp.com/work/vanguard-ngr/

Do you mind sharing this version of nginx-helper? Could be helpful, if you are fine with it.

**Comment by rsmith4321** [comment] 2019-04-24 18:57
This was like 3 years ago I don't use mobile detection anymore.

**Comment by ggloveswp** [comment] 2019-04-25 02:32
@rsmith4321 Sure. That was actually a ping for @rahul286 

Whereas in most cases, this is not needed anymore, I was just curious if can someone share a purging solution based on the above, since I faced a similar setup lately: 

Its purpose of implementation was to serve desktop version to every other visitor, except if he was using a mobile device. For specific mobile devices that match a filter, a third version of the website should be served, providing different code than the responsive version.

Those filters were applied in order to prevent older mobile devices from loading a complete responsive version of the website that would slow them down, so for this purpose, they had to separate Redis desktop/mobile keys and they can still clear it completely, but they are unable to auto-purge upon new post using nginx-helper, just because of the added key.

**Comment by kirtangajjar** [comment] 2019-04-27 06:18
Hey @ggloveswp, You can check [this quick doc](https://docs.google.com/document/d/1yIBHCpNjbiX6P8ZQUwXyeGLcM9q_KP0oYmsdDwR31wU/edit?ts=5cc2ee4b#heading=h.985t1j7qa26x
) we've written. It describes how you can solve this particular problem on EE4. 

Although for now, this solution includes modifying files of the nginx-helper plugin, there is an upcoming version of the plugin which will add filters so that you won't have to modify the plugin files.

**Comment by ggloveswp** [comment] 2019-04-27 22:50
> Hey @ggloveswp, You can check [this quick doc](https://docs.google.com/document/d/1yIBHCpNjbiX6P8ZQUwXyeGLcM9q_KP0oYmsdDwR31wU/edit?ts=5cc2ee4b#heading=h.985t1j7qa26x) we've written. It describes how you can solve this particular problem on EE4.
> 
> Although for now, this solution includes modifying files of the nginx-helper plugin, there is an upcoming version of the plugin which will add filters so that you won't have to modify the plugin files.

Lots of thanks for your awesome reply and your helpful guide. 
Im still using EEv3 due to the nature of this project that is not able to welcome a dockerized setup, but it worked flawlessly on different paths.

**Comment by ggloveswp** [comment] 2019-06-15 10:01
@kirtangajjar bumping this thread up to ask you how do you handle device detection based on useragent and non-webp-supported browsers.
