### ISSUE TITLE
ee uninstall option

### ISSUE THREAD

**Issue by anantshri** [EasyEngine/easyengine#488] opened 2015-04-11 13:38 UTC
There should be an option if someone wants to completly remove ee from the system.

You might want to warn them but let the user have an option to remove ee completely.

**Comment by joseph-jalbert** [comment] 2015-04-23 16:35
+1

**Comment by MattyLB** [comment] 2015-04-23 20:02
+1 (including all stacks ee installed)

**Comment by rahul286** [comment] 2015-04-24 07:31
Can anyone please write synopsis for uninstall process?

Some questions we need to answer:

1. What will happen to mysql (data) when we install mysql server?
2. What will happen to website files if we need to delete `/var/www`?
3. What will happen to nginx, php, mysql and other config files?
3. If all sites' files and database need to be deleted then why not recreate/format VPS/dedicated server?

Basically, I want to know what a user expects afte easyengine is uninstalled. Since I never need to uninstall easyengine, I find this case harder to imagine.

Uninstall coding is not big deal. We already have commands like `ee stack purge` and also `ee site update-all` to deal with all sites. We can reuse there code to remove everything from server. But again need to be removed and what need to left behind?

**Comment by ugommirikwe** [comment] 2015-04-30 10:01
I think it's unethical to not provide an easy way for a program to be uninstalled, having provided an easy way for it to be installed in the first place. Only malware act like that :-(

**Comment by rahul286** [comment] 2015-05-01 15:12
@ugommirikwe Thanks for comparing EasyEngine to malware. BTW EE codes are open source so can you please care to point out what it malware like activity EE does?

Also, did you care to check my comment above your comment? https://github.com/rtCamp/easyengine/issues/488#issuecomment-95834528

If you can't answer questions I asked in my comment, do not expect us to work on this.

We have more important things to take care. So anyone who needs this badly can send pull-request or atleast answer https://github.com/rtCamp/easyengine/issues/488#issuecomment-95834528

Sorry but I need to know what people expect when they wish to run `ee uninstall`!

**Comment by rahul286** [comment] 2015-05-01 15:13
@anantshri as you started this, please answer https://github.com/rtCamp/easyengine/issues/488#issuecomment-95834528

**Comment by rahul286** [comment] 2015-05-01 15:15
@joseph-jalbert `ee system remove` will remove all packages like nginx, php, mysql EE installs. EE code remains on server itself.

**Comment by rahul286** [comment] 2015-05-01 15:16
@MattyLB if EE install removes all stacks installed, what will happen to sites? They should simply become unreachable or deleted as well?

**Comment by MattyLB** [comment] 2015-05-01 15:51
OPTION 1:
as long as we could have all of our site-specific config files,
certificates and content reside within the /var/www/example.com/...
directory tree, those files wouldn't need to be touched.

upon re-installing ee (to fix an issue caused by upgrade, corrupted main
config, file or otherwise) those would be replaced independently of any
existing sites.

when the reinstall of ee is completed satisfactorily, I believe the best
way to "reactivate" the site(s) in /var/www/... is to run a script like "ee
site discover --enable --prompt --etc" so we can choose to reactivate all
existing sites or be prompted to choose which ones to enable. Each site
could have a simple manifest file that tells ee exactly what needs to be
configured for the site, eg. db user & pw, hhvm, nginx, pagespeed, etc.
- - - - -
OPTION 2:
if that can't be done, a simple warning to backup our site data would
suffice - because in all honestly - our only alternative when we run into a
major malfunction is to create a new instance or refresh the server anyway.
:)

**Comment by rahul286** [comment] 2015-05-01 16:07
@MattyLB Uninstalling and reinstalling are different things. EE installation expects a clean system. Not even traces of old EE system are handled as of now. So Option 1 will be a lot of work.

**About option 2:** we have some other plan in pipeline which might help here. There will be a command to move all EE sites from one EE server to another EE server seamlessly.

**Comment by MattyLB** [comment] 2015-05-01 16:15
+1 - that would be a big help.  In my particular case, I use AWS and while
it's easy enough to simply create a new EC2 instance, there is a lot of
work to the get my sites back up and certificates placed, etc. so the
migration method you speak of would be a great help! :)

**Comment by MattyLB** [comment] 2015-05-01 17:17
One of the reasons this is of interest to me is when issue like this most
recent one occur that happened after upgrading from 3.1.0 to 3.1.2...


>  # ee site create xxxxxx.com --wpfc --hhvm --pagespeed
>
Adding repository for MySQL, please wait...
> Updating apt-cache, please wait...
> Installing packages, please wait...
> *Reload : mysql     [Failed]*
> Setting up NGINX configuration  [Done]
> Setting up webroot              [Done]
> Downloading Wordpress           [Done]
> *Setting up database             (2003, "Can't connect to MySQL server on
> 'localhost' (111)")*
>

so I tried this ...

> root@ip-172-31-27-174:~# ee stack install
> Nginx already installed
> PHP already installed
> HHVM already installed
> Postfix is already installed
> WP-CLI is already installed
> Adding repository for MySQL, please wait...
> Updating apt-cache, please wait...
> Installing packages, please wait...
> Downloading phpMyAdmin           [Done]
> Downloading Adminer              [Done]
> Downloading phpMemcachedAdmin    [Done]
> Downloading clean.php            [Done]
> Downloading opcache.php          [Done]
> Downloading Opgui                [Done]
> Downloading OCP.php              [Done]
> Downloading Webgrind             [Done]
> Downloading pt-query-advisor     [Done]
> Downloading Anemometer           [Done]
> *Reload : mysql     [Failed]*
> *(2003, "Can't connect to MySQL server on 'localhost' (111)")*
>
>
now my only solution is to go into AWS, create a new EC2 instance and
"hope" this doesn't happen again. It becomes a pain, which is why a method
to start from scratch (eg. uninstall EE and any stacks installed by EE
*might* be an easier way for people facing the same issues).

**Comment by anantshri** [comment] 2015-05-02 04:15
hey @rahul286, kept delaying this message coz i thought this need more consideration then my initial comment. So here are couple of scenario's i can think off.

1) Considering EE as just yet another software, just like we have an installation option, we should have uninstall option. one case in consideration. a user installed ee as per instructions but due to one or the other reason (in my case https://github.com/rtCamp/easyengine/issues/489) so he is stopped in mid way or rather at the start. What is the safe way to remove all traces of ee as user has not even started using it but decided not to use it anymore.

2) Consider at one point in usage the user decides that they don't want this tool. removing stacks is one thing what about custom config's added by ee how can we ensure all those config based on say a user input is either nuked or retained. may be we are already doing it or we need to do a backup of old config and restore when person say remove ee.

3) as for the question why not a new instance why remove it. Multiple reason's including the fact that ee might be part of hybrid environment where other configurations would take time even if that means running a vagrant + ansible job list but still time taken to rebuild stack. 

However i agree with you that its not easy to decide what to keep and what to remove. Here i would suggest we make backup of all configuration file that we touch during the life cycle of ee at the time of installation and if asked to uninstall ask user if they want config to be reverted. However an edge case would be if user has tampered with config but still want to retain his custom stuff. in that case i would suggest (if we are not doing that already) to mark sections added by ee as seperate may be how wordpress keeps sections in .htaccess. with a warning don't tempare here it will be overwritten. and use that as pointers to the section to be nuked. 

I hope this long rand makes some sense.

**Comment by MattyLB** [comment] 2015-05-02 05:16
In regards to the second paragraph of @Anant's point #3, this is what I
meant by creating a manifest for each site that keeps track of site
specific services, config changes, WP settings, DB settings, certificate
locations etc, and it would reside in the /var/www site folder that
wouldn't need to be deleted by the ee uninstaller. It could then be
referenced if we installed ee again to bring the site(s) back up with
current ee features, stacks and base configs.

**Comment by rahul286** [comment] 2015-05-02 09:37
> It could then be referenced if we installed ee again to bring the site(s) back up with current ee features, stacks and base configs.

Anything in this direction will take huge amount of time. Currently we do not have a big team to purse something like this. Specially for uninstallation process. 

@ALL 

Here is what we are thinking as of now:

-[ ] `ee uninstall` => display contextual help 
-[ ] `ee uninstall --stack` => removes EE + all packages installed
-[ ] `ee uninstall --site` => removes EE + all sites created (files + db)
-[ ] `ee uninstall --site --stack` => removes EE + all packages installed + all sites created (files + db)
-[ ] `ee uninstall --all` => alias to `ee uninstall --site --stack`

`ee uninstall` will need some sort of security. I am thinking of few way like:

1. Forcing ee config to have a line like `uninstall = true`
2. Prompting for confirmation (remote uninstall will not work unless we provide command line `--force` switch)
3. Using some ASCII generation logic to emulate CAPTCHA like thing.

A different option we are thinking of is to maintain an external shell script. If anybody want to uninstall easyengine they can download and run that script on EE server.

By the way, WordPress and many other softwares do not provide any "uninstaller" and that doesn't make them malware. So "uninstaller" is must is not enough reason to code one.

I am concerned that if a server gets hacked, attacker can wipe everything out very easily by running `ee uninstall` command! I am aware, attacker can do same damage in absence of this command as well. 

Overall, this issue has lowest priority for us. So unless I am 100% sure that `ee uninstall` won't result in accidental data loss, we won't add it.

**Comment by xihad76** [comment] 2015-05-15 17:11
Right now is there any way to reinstall ee script?
I am afraid ee not working as expected after upgrading it. For example I can not access admin tools anymore. Later I found out ee didnt add nginx configuration for 22222 though created the web directory in /var/www. Also I can not create new site anymore. It throws error in database creation part.

**Comment by ugommirikwe** [comment] 2015-05-16 13:58
@rahul286 I'm sorry my comment came out the way it did - the malware thing. Didn't intend to denigrate you or your effort in providing this tool. Indeed, it is an awesome tool.

Just that non-expert *nix users have come to rely on commands like "apt-get remove" or "apt-get purge" to get rid of installations they no longer need, so as to prevent it from messing up other stuffs on their servers. The frustration of not having that with a tool like EE, which seems to perform a lotta "magic" behind the scenes, completely ticked me off. My installation using EE was mangled originally, so needed to remove it and be sure I can start all over again with or without EE. Maybe you can appreciate the frustration.

In any case, I'm sorry; EE is in no way a malware :-) as far as I can tell. Keep up the effort.

**Comment by crapthings** [comment] 2015-06-01 15:07
i want to reinstall whole thing because i can't get nginx to run. it failed at site create.

**Comment by CelticParser** [comment] 2016-05-19 02:01
+1 
**Reason(s):** 
 - Easy; **UX** (_prevent an entire server wipe to get rid of it - Had a few clients insisting on it_).
 - `ee system remove` **hasn't been supported for many versions ago**
    - `usage: ee (sub-commands ...) [options ...] {arguments ...}
       ee: error: unrecognized arguments: system remove`

**Comment by rahul286** [comment] 2016-05-19 06:13
@CelticParser `ee system` is replaced by `ee stack`. Try that.

**Comment by CelticParser** [comment] 2016-05-19 16:16
@rahul286  

See above comment:[220208797](https://github.com/EasyEngine/easyengine/issues/488#issuecomment-220208797)

> ee system remove hasn't been supported for many versions ago
> usage: ee (sub-commands ...) [options ...] {arguments ...} ee: error: unrecognized arguments: system remove

**Comment by suniel** [comment] 2016-08-24 19:05
Hi there @rahul286 
I am bit confused here.
I already had LEMP setup on my machine.
Then I came across EasyEngine found it really useful :+1: 
But I already had LEMP setup. So I wanted to uninstall it.
Will ee uninstall --stack remove all my pre-installed LEMP stacks.

**Comment by w33zy** [comment] 2016-08-24 20:09
@suniel 

You'll have to uninstall everything yourself and ````ee```` has its own configs for the LEMP apps. For this reason it is a good idea to start with a fresh install of Ubuntu

**Comment by AngelODeath** [comment] 2016-09-13 13:22
I have this issue now.
I already had a LEMP stack installed
Then I installed ee using the recommended method: `wget -qO ee rt.cx/ee && sudo bash ee`
Now I wanted to remove ee from my system, but keep my previously instelled LEMP stack
So I ran `sudo ee stack remove`
Got error: `Cannot Remove! Nginx Stable version not found.`

Run `sudo ee stack status`
Got: `Nginx is not installed
HHVM is not installed
php5.6-fpm:  Running
php7.0-fpm:  Running
mysql     :  Running
postfix   :  Running`

Problem is, This is not what I wanted, I need my `nginx` and `HVVM` back, but I do not want the `ee` file on my system anymore.

`which ee`
`/usr/local/bin/ee`

ee is still on my system

`dpkg` and `apt` does not show `EasyEngine` or `ee` as being installed

I think I need to do a whole reinstallation of linux, what the hell???
Please can you list all files and folders created by `EasyEngine` so I can remove them manually.

This is quite frustrating!

Regards
Angel Of Death

**Comment by AngelODeath** [comment] 2016-09-13 13:30
I found this page:
[http://www.galih.us/2014/12/cara-uninstall-easyengine.html](url)

But I do not know what language it is... Anyway

So this seems to be what they suggest:
First:
`sudo ee system purge`

Then:
`sudo rm -rf /etc/easyengine/`
`sudo rm -rf /etc/bash_completion.d/ee`
`sudo rm -rf /usr/local/sbin/ee`
`sudo rm -rf /usr/local/sbin/easyengine`
`sudo rm -rf /usr/share/easyengine`
`sudo rm -rf /var/www/*`
`sudo rm -rf /etc/nginx`
`sudo rm -rf /etc/php5`
`sudo rm -rf /etc/mysql`
`sudo rm -rf /var/lib/mysql`
`sudo rm -rf /etc/postfix`

And finally:
`sudo apt-get autoremove`

Hope this helps someone

**Comment by EBuzznet67** [comment] 2018-01-03 18:55
AngelODeath - your answer does not work. Still getting example.com is exist

**Comment by rahul286** [comment] 2018-05-29 08:31
We are cleaning up issue tracker and closing this one because we couldn't reach an agreement as what exactly needs to be removed when EasyEngine needs to uninstalled.

The best way for users is to start a fresh VPS, move content (source + files + DB) to the new system and just destroy the old machine.

We would be happy to review this topic again if somebody sends a detailed proposal which outlines all practical scenarios.

**Closed by rahul286** 2018-05-29 08:31 UTC

**Comment by rahul286** [comment] 2018-08-14 09:00
**Update:** We have added this option in v4 https://github.com/EasyEngine/easyengine/issues/1125

Since v4 is docker based, its very easy to do a clean uninstall.

**Comment by jonathanhatch** [comment] 2019-02-27 21:40
> **Update:** We have added this option in v4 #1125
> 
> Since v4 is docker based, its very easy to do a clean uninstall.

Great. Can you tell me how?

**Comment by mrrobot47** [comment] 2019-02-28 05:46
@jonathanhatch https://easyengine.io/commands/cli/self-uninstall

**Comment by jonathanhatch** [comment] 2019-02-28 14:59
> @jonathanhatch https://easyengine.io/commands/cli/self-uninstall

You're the best. Thank you, sir!

**Comment by ZinkDifferent** [comment] 2019-08-14 21:08
> @anantshri as you started this, please answer [#488 (comment)](https://github.com/EasyEngine/easyengine/issues/488#issuecomment-95834528)

"Oops! That page can’t be found."
