### ISSUE TITLE
Unable to query database on Ubuntu 14.04

### ISSUE THREAD

**Issue by trst** [EasyEngine/easyengine#693] opened 2016-03-30 18:08 UTC
I've been receiving the error `Unable to query database` on my VPS when I try to run any commands related to any of my sites. The trouble happened after I updated to the latest version of Easyengine and switched to nginxmainline for HTTP/2 and Letsencrypt on one domain. I don't think that the two are necessarily connected, seeing as this appears to be a database issue.

I was thinking of blowing out the database and starting anew, but if there's away to save my configuration I'm all ears.

Thanks!

***

Ubuntu 14.04.4 LTS
EasyEngine v3.5.4
NGINX (1.9.10):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.19-7):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.13-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             1
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

**Comment by iam404** [comment] 2016-04-13 08:41
Hii @trst

It looks like recent EasyEngine update had error on your VPS server. Can you run below command manually and check if that solved your problem.

`echo "ALTER TABLE sites ADD COLUMN php_version varchar DEFAULT "5.6";" | sqlite3 /var/lib/ee/ee.db`

As we cannot reproduce this on our testing servers, I am closing this issue for now. For any other queries you can use our support forum http://community.rtcamp.com/c/easyengine

**Closed by iam404** 2016-04-13 08:41 UTC
