### ISSUE TITLE
Add node.js/websockets/ghost support to ee site templates

### ISSUE THREAD

**Issue by ichpen** [EasyEngine/easyengine#628] opened 2015-10-05 20:11 UTC
Given growing popularity of node/websockets/ghost etc sites would be nice to have some support out of the box for ee. Currently the process involves some edits of nginx conf files to have forwarding and proxying working properly.

**Comment by cm896** [comment] 2015-10-05 20:42
+1

**Comment by ichpen** [comment] 2015-11-03 01:13
Shouldn't be hard to implement guys :) Extend the proxy template, add a target host/port parameter and some extra nginx directives. For node/ghost etc the below is usually enough.

location / {
        proxy_pass http://APP_PRIVATE_IP_ADDRESS:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

**Comment by janiosarmento** [comment] 2016-03-29 14:32
Any news regarding this?

I've got some Ghost blogs to configure, and if EE could do the dirty work for me it would be great.

**Comment by rahul286** [comment] 2018-05-29 12:16
Note: This can be done as an EE Package in v4.

**Comment by rahul286** [comment] 2018-05-29 12:16
Duplicate of #319

**Closed by rahul286** 2018-05-29 12:16 UTC
