### ISSUE TITLE
Cloudflare & up to date IP ranges

### ISSUE THREAD

**Issue by ggloveswp** [EasyEngine/easyengine#996] opened 2018-04-20 08:09 UTC
**Description:** If you are behind Cloudflare service, you may have already applied a solution in order to get visitor's real IP.
However, these IP ranges can be changed at anytime, in case CF decides so (blacklisting purposes etc).

**Workaround:** Instead of creating a static config file that is included in nginx's config, I suggest the following way, which will be updating itself based on a cronjob.

**Commands:**
```
cd /root/
wget https://gist.github.com/irazasyed/fc73419d0d92f607c495/raw/2d2495c69eef44eaad50a9fa6ff821e6ae007d74/cf-ip-ranges-updater.sh
chmod +x cf-ip-ranges-updater.sh
./cf-ip-ranges-updater.sh
```

Finally, include your new config file in server block of nginx:
`include /etc/nginx/cloudflare-ips.conf;`

And add a cronjob so cf-ipranges-updater.sh will be executed regularly:
`50 0 * * * /root/cf-ip-ranges-updater.sh`

**Comment by VirtuBox** [comment] 2018-04-20 14:53
Isn't it easier to create  a cloudflare.conf file in /etc/nginx/conf.d/ to not have to include it manually in nginx configuration. 

There is also a similar script for ufw : https://github.com/Paul-Reed/cloudflare-ufw/
Because with fail2ban, or a rate limiter on nginx, it happen to ban some cloudflare IPs

**Comment by kirtangajjar** [comment] 2018-11-23 15:37
Closing this as it's a duplicate of https://github.com/EasyEngine/easyengine/issues/646

**Closed by kirtangajjar** 2018-11-23 15:37 UTC
Labels: kind/feature
