### ISSUE TITLE
Update of EasyEngine removes ownCloud and Roundcube.

### ISSUE THREAD

**Issue by marbetschar** [EasyEngine/easyengine#682] opened 2016-02-29 10:20 UTC
I've just executed the `sudo ee update` command to get the all new php7 support.
Unfortunately this removed the packages owncloud & roundcube from my server!

If I try to install the owncloud package again the dependency resolution is broken; just claiming I can't do it at all:

```
The following packages have unmet dependencies:
 owncloud-server : Depends: php5-cgi but it is not going to be installed
```

Executing `apt-get -f install`doesn't fix the error either. Please help, our entire customer backed ownCloud service is broken now!
- lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```
- ee -v

```
EasyEngine v3.5.2
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.
```
- ee info

```
NGINX (1.8.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             1g
allow                            127.0.0.1 83.150.63.67

PHP (5.6.18-9):

user
expose_php                       Off
memory_limit                     512M
post_max_size                    1G
upload_max_filesize              1G
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.0.21-MariaDB) on localhost:

port                             3306
wait_timeout                     1800
interactive_timeout              60
max_used_connections             95
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
```
- wp --allow-root --info

```
PHP binary: /usr/bin/php5.6
PHP version:    5.6.18-9+deb.sury.org~trusty+1
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.21.1
```

**Comment by janiosarmento** [comment] 2016-03-02 16:36
Did you check if the new version (3.5.3) fixed your issue?

**Comment by marbetschar** [comment] 2016-03-07 11:00
Unfortunately no success, even after the update. This is what I get:

```
root@Hosting:/var/www# apt-get install owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.2.2-1.1) but it is not going to be installed
            Recommends: owncloud-config-apache (= 8.2.2-1.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


root@Hosting:/var/www# apt-get install owncloud-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-server : Depends: php5-cgi but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


root@Hosting:/var/www# apt-get install php5-cgi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-cgi : Depends: php5-common (= 5.5.9+dfsg-1ubuntu4.14) but 5.6.18+dfsg-1+deb.sury.org~trusty+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by iam404** [comment] 2016-03-07 11:32
Hii @marbetschar 

We are not able to reproduce your issue. Owncloud get installed perfectly on our instance.

```
root@vagrant-ubuntu-trusty-64:# apt-get install owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  owncloud
0 upgraded, 1 newly installed, 0 to remove and 89 not upgraded.
Need to get 35.5 kB of archives.
After this operation, 191 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe owncloud all 6.0.1+dfsg-1ubuntu1.2 [35.5 kB]
Fetched 35.5 kB in 0s (73.2 kB/s)
Preconfiguring packages ...
Selecting previously unselected package owncloud.
(Reading database ... 67259 files and directories currently installed.)
Preparing to unpack .../owncloud_6.0.1+dfsg-1ubuntu1.2_all.deb ...
Unpacking owncloud (6.0.1+dfsg-1ubuntu1.2) ...
Setting up owncloud (6.0.1+dfsg-1ubuntu1.2) ...
```

`php5-cgi : Depends: php5-common` this php version has been depreciated in latest version of easyengine.

Also can you try changing the repository you are using for OwnCloud.

**Comment by marbetschar** [comment] 2016-03-07 14:23
Hi @iam404 

Thanks for the feedback. Yes, it seems to be related to the deprecation of the php version. I had php5.6 installed together with Easy Engine and ownCloud on the system. php5.6 seems to be still a dependency of ownCloud.

Then I've updated Easy Engine to the first release supporting php7. During this update ownCloud was deinstalled - maybe due to the deprecation of php5.6 from Easy Engine...?

**FWIW: Roundcube was deinstalled during this Easy Engine update process too. Now I can't get it installed either - seems to be the same reason.**

And now I'm a bit lost in space, since I can't get apt to install ownCloud again for some reason.
I've forced the ownCloud install now by using `dpkg --ignore-depends` - but the system seems to be corrupted somehow now.

I'm using the following repo url for ownCloud - which other may I try?`

`deb http://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/ /`

**Comment by marbetschar** [comment] 2016-03-07 14:27
Can you please elaborate the following line of my previously posted logs:

`php5-cgi : Depends: php5-common (= 5.5.9+dfsg-1ubuntu4.14) but 5.6.18+dfsg-1+deb.sury.org~trusty+1 is to be installed`

Why is `apt` forced to install a php version which does not met the dependencies? Maybe sorting this out would resolve the whole issue?

**Comment by marbetschar** [comment] 2016-03-10 13:08
Any news on this one? Roundcube & ownCloud are still not working :(

**Comment by timelf123** [comment] 2016-07-27 21:32
Still not working

**Comment by rahul286** [comment] 2018-05-29 08:42
We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.

**Closed by rahul286** 2018-05-29 08:42 UTC
