### ISSUE TITLE
Can't install mail packages

### ISSUE THREAD

**Issue by marciomarim** [EasyEngine/easyengine#673] opened 2016-02-02 09:12 UTC
Hi, 

First of all thanks for EE, it's a very good tool!

Now I'm running a fresh Ubuntu install (2Gb) and everything is working but I can't get to install the mail packages. I tried many times:

```
sudo ee stack remove --mail
sudo ee stack purge --mail
sudo ee stack install --mail
```

I get this message at the end:
`Restart : amavis    'ascii' codec can't decode byte 0xe2 in position 67: ordinal not in range(128)`

I have nothing in the logs about this error and the folder /var/www/22222/htdocs there is only:
`cache db fpm php`
So when I go to mydomain.com:22222/vimbadmin I get an 404 page not found.

Any ideas ? Many thanks.
Marcio

**Comment by oh3netid** [comment] 2016-06-17 06:03
Hello, I'm having the same issue on a fresh install of Debian 8.5 (2GB). Here is the tail of my ee.log

```
Setting up mariadb-server (10.1.14+maria-1~jessie) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for php5-fpm (5.6.22+dfsg-0+deb8u1) ...
Processing triggers for dovecot-core (1:2.2.13-12~deb8u1) ...
Errors were encountered while processing:
 amavisd-new
E: Sub-process /usr/bin/dpkg returned an error code (1)
2016-06-17 01:52:23,178 (INFO) ee : Oops Something went wrong!!
2016-06-17 01:52:23,180 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

**Comment by iam404** [comment] 2016-06-17 06:40
@arush-sal please check the above issue on all distro.

**Comment by arush-sal** [comment] 2016-06-17 10:05
@oh3netid @iam404 I tried to reproduce the error both in wheezy and jessie but seems everything is working fine on my end.

```
vagrant@debian-wheezy:~$ sudo ee stack install --mailscanner 
Updating apt-cache, please wait...
Installing packages, please wait...
Restart : dovecot   [OK]
Reload : postfix   [OK]
Restart : amavis    [OK]
Successfully installed packages
vagrant@debian-wheezy:~$ logout
```

```
vagrant@debian-jessie:~$ sudo ee stack install --mailscanner 
Updating apt-cache, please wait...
Installing packages, please wait...
Restart : dovecot   [OK]
Reload : postfix   [OK]
Restart : amavis    [OK]
Successfully installed packages
```

**Comment by oh3netid** [comment] 2016-06-19 02:04
@arush-sal Thank you. It does seem to work correctly with a vagrant deployed image. But I get the amavisd-new error when doing ``ee stack install --mail`` on Vultr or Digitalocean.

**Comment by ThiagohrMartins** [comment] 2016-08-19 20:24
I have the same problem! Somebody?

**Comment by Wemago** [comment] 2017-03-12 04:44
Did anyone solved this? Tried different ways to install using email stack but none worked.

@gooderist did you manage to get a solution? What you say there didn't help me

**Comment by rahul286** [comment] 2018-05-29 08:43
We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.

**Closed by rahul286** 2018-05-29 08:43 UTC
