### ISSUE TITLE
Update completely destroyed PHP

### ISSUE THREAD

**Issue by justnorris** [EasyEngine/easyengine#695] opened 2016-03-31 17:56 UTC
I can't even isntall PHP Anymore:
~~~
Do you want to continue? [Y/n]
Get:1 http://mirrors.linode.com/ubuntu/ trusty-backports/universe php5-apcu amd64 4.0.7-1build1~ubuntu14.04.1 [78.3 kB]
Get:2 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main php5-common amd64 5.5.34+dfsg-1+deb.sury.org~trusty+1 [679 kB]
Fetched 757 kB in 1s (441 kB/s)
Selecting previously unselected package php5-common.
(Reading database ... 39127 files and directories currently installed.)
Preparing to unpack .../php5-common_5.5.34+dfsg-1+deb.sury.org~trusty+1_amd64.deb ...
Unpacking php5-common (5.5.34+dfsg-1+deb.sury.org~trusty+1) ...
Selecting previously unselected package php5-apcu.
Preparing to unpack .../php5-apcu_4.0.7-1build1~ubuntu14.04.1_amd64.deb ...
Unpacking php5-apcu (4.0.7-1build1~ubuntu14.04.1) ...
Setting up php5.6-cli (5.6.20+dfsg-1+deb.sury.org~trusty+1) ...
Error: The new file /usr/lib/php/5.6/php.ini-production.cli does not exist!
dpkg: error processing package php5.6-cli (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of php5.6-fpm:
 php5.6-fpm depends on php5.6-cli; however:
  Package php5.6-cli is not configured yet.

dpkg: error processing package php5.6-fpm (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-igbinary:
 php-igbinary depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-igbinary (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-imagick:
 php-imagick depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-imagick (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-memcache:
 php-memcache depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-memcache (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-msgpack:
 php-msgpack depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-msgpack (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-memcached:
 php-memcached depends on php-igbinary; however:
  Package php-igbinary is not configured yet.
 php-memcached depends on php-msgpack; however:
  Package php-msgpack is not configured yet.
 php-memcached depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-memcached (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-pear:
 php-pear depends on php-cli; however:
  Package php-cli is not installed.
  Package php5.6-cli which provides php-cli is not configured yet.

dpkg: error processing package php-pear (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php-xdebug:
 php-xdebug depends on phpapi-20151012 | phpapi-20131226; however:
  Package phpapi-20151012 is not installed.
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php-xdebug (--configure):
 dependency problems - leaving unconfigured
Setting up php5-common (5.5.34+dfsg-1+deb.sury.org~trusty+1) ...

Creating config file /etc/php5/mods-available/pdo.ini with new version

Creating config file /etc/php5/mods-available/opcache.ini with new version
Setting up php5-apcu (4.0.7-1build1~ubuntu14.04.1) ...
dpkg: dependency problems prevent configuration of php5.6-json:
 php5.6-json depends on phpapi-20131226; however:
  Package phpapi-20131226 is not installed.
  Package php5.6-fpm which provides phpapi-20131226 is not configured yet.
  Package php5.6-cli which provides phpapi-20131226 is not configured yet.

dpkg: error processing package php5.6-json (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 php5.6-cli
 php5.6-fpm
 php-igbinary
 php-imagick
 php-memcache
 php-msgpack
 php-memcached
 php-pear
 php-xdebug
 php5.6-json
E: Sub-process /usr/bin/dpkg returned an error code (1)
~~~

~~~
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
You have new mail.
~~~

~~~
$ ee -v
EasyEngine v3.5.4
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.
~~~

~~~
$ ee info
grep: /etc/nginx/common/acl.conf: No such file or directory

NGINX (1.8.1):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow
'PHP'
~~~

~~~
$ wp --allow-root --info
zsh: command not found: wp
~~~

**Comment by fuentesbr** [comment] 2016-03-31 18:11
I have same problem:

Setting up libphp7.0-embed (7.0.5-1+deb.sury.org~trusty+1) ...
Error: The new file /usr/lib/php/7.0/php.ini-production does not exist!
dpkg: error processing package libphp7.0-embed (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up php5.6-cli (5.6.20+dfsg-1+deb.sury.org~trusty+1) ...
Error: The new file /usr/lib/php/5.6/php.ini-production.cli does not exist!
dpkg: error processing package php5.6-cli (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of php5.6-fpm:
 php5.6-fpm depends on php5.6-cli; however:
  Package php5.6-cli is not configured yet.

dpkg: error processing package php5.6-fpm (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 libphp7.0-embed
 php5.6-cli
 php5.6-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by janiosarmento** [comment] 2016-03-31 20:26
Not just you. It seems to be a general failure on some repo.

**Comment by iam404** [comment] 2016-04-01 09:21
Please try installing PHP now. As we are not able to reproduce the above on any platform, I am closing this issue.

**Closed by iam404** 2016-04-01 09:21 UTC
