### ISSUE TITLE
Can't create a new site on a new EasyEngine Install Debian 8

### ISSUE THREAD

**Issue by ikolubr** [EasyEngine/easyengine#892] opened 2017-07-21 18:07 UTC
Command
ee site create example.com --mysql --php7

EE log
easyengine nginx-common (= 1.10.3-10ppa~stable) but 1.12.1-1~dotdeb+8.1 is to be installed E: Unable to correct problems, you have held broken packages.

Please attach the output of following command when open a new support request.

- [No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie ] lsb_release -a
- [ EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.] ee -v
- [grep: /etc/nginx/common/acl.conf: No such file or directory

NGINX (1):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            
PHP5 is not installed ] ee info
- [ ] wp --allow-root --info

**Comment by VirtuBox** [comment] 2017-07-21 21:14
Issue is caused by dotdeb.org nginx package new release : 
http://community.rtcamp.com/t/warning-easyengine-on-debian-8-jessie-packages/9171

**Comment by ikolubr** [comment] 2017-07-21 21:37
Thank you.
For some reason, running ee stack install --nginx first, llet me create a site without problems. Weird.

Thank you,

**Comment by VirtuBox** [comment] 2017-07-21 22:28
Because dotdeb repository is not added when you launched the nginx installation

**Comment by mbtamuli** [comment] 2018-05-29 11:03
I hope this issue is resolved. Closing this issue.

**Closed by mbtamuli** 2018-05-29 11:03 UTC
