### ISSUE TITLE
Unable to correct problems, you have held broken packages - after trying to install stack 

### ISSUE THREAD

**Issue by przemekcichon** [EasyEngine/easyengine#683] opened 2016-03-01 16:04 UTC
Hi, 

I am trying to install stack and I get the following after running the command `sudo ee stack install`
```
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

and here is what is inside of the ee.log file:
```
php5.6-mcrypt : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-mysql : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-opcache : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-readline : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-recode : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-xml : Depends: php-common (>= 1:33) but it is not going to be installed
 php5.6-zip : Depends: php-common (>= 1:33) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
2016-03-01 16:01:40,717 (INFO) ee : Oops Something went wrong!!
2016-03-01 16:01:40,717 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

And I did try several times.

Would you be able to help me with it?

Please note that this is fresh install of the unbuntu server on virtualbox

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
- [ ] ee -v
```
EasyEngine v3.5.2
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.
```
- [ ] ee info
```
Nginx is not installed
```
- [ ] wp --allow-root --info
```
wp: command not found
```

**Comment by caaol** [comment] 2016-03-01 18:16
I have the same problem.

The following packages have unmet dependencies:
php-common : Breaks: php-memcached (< 2.2.0-95-g6ace07d+2.2.0-2~) but 2.2.0-95-g6ace07d+2.2.0-1+deb.sury.org~trusty+1 is to be installed
php-memcached : Depends: php-igbinary but it is not going to be installed
Depends: php-json
php5.6-fpm : Depends: php5.6-json but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by janiosarmento** [comment] 2016-03-01 18:43
I'm not in a fresh install, but after upgrading to EE 3.5.2 the very same issues appeared.

**Comment by janiosarmento** [comment] 2016-03-01 18:47
apt-get install php7.0
    apt-get install php5.6

The commands above did work for me.

**Comment by przemekcichon** [comment] 2016-03-01 19:36
Thank you Janio! This worked for me as well.

**Comment by harshadyeola** [comment] 2016-03-01 19:41
seems like latest package updates with php repo. some major changes.
https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by janiosarmento** [comment] 2016-03-01 20:27
I'm sorry, but is it possible to workaround this issue in EE? What should we users do?

Thanks, @harshadyeola. :)

**Comment by janiosarmento** [comment] 2016-03-01 20:30
Another bit of information: wp-cli doesn't work anymore. :( It complaints there is no MySQL extension compiled in PHP.

**Comment by janiosarmento** [comment] 2016-03-01 20:33
apt-get install php7.0-mysql php7.0-json php7.0-bcmath php7.0-curl php7.0-common php7.0-mbstring php7.0-mcrypt

The above fixed wp-cli to me.

**Comment by adamspruijt** [comment] 2016-03-01 21:25
Thanks @janiosarmento so far your suggestions have atleast got my ee admin working, but sites are now downloading php files instead of executing. Some mess. Ill report back if I get anywhere with this.

**Comment by janiosarmento** [comment] 2016-03-01 21:53
@adamspruijt try enabling HHVM on your sites; this will reconfigure the vhost file, and with a bit of luck solve your issue of downloading php files.

    ee site update example.com --hhvm

**Comment by adamspruijt** [comment] 2016-03-02 00:24
@janiosarmento interesting, I will try this when I am back in office tomorrow and let you know how it goes. Was actually considering trying out HHVM regardless, thanks!

**Comment by harshadyeola** [comment] 2016-03-02 04:46
@janiosarmento 
EasyEngine PHP7 Stack installs the packages you mentioned. So no need to install these manually.
Will check with the changes in PHP Repo to get the fix.
 `apt-get install php7.0-mysql php7.0-json php7.0-bcmath php7.0-curl php7.0-common php7.0-mbstring php7.0-mcrypt
`

**Comment by oerdnj** [comment] 2016-03-02 06:23
This has been fixed in the last php-memcached upload and all packages from ppa:ondrej/php should be fine again.

**Comment by harshadyeola** [comment] 2016-03-02 06:25
@oerdnj: Thanks :+1:

**Closed** 2016-03-02 06:26 UTC
