### ISSUE TITLE
[Feature Request] ElasticSearch as native EasyEngine option | --elasticsearch / -es

### ISSUE THREAD

**Issue by michacassola** [EasyEngine/easyengine#1002] opened 2018-05-08 19:45 UTC
Can we have ElasticSearch as a native --elasticsearch option for EE 4.0 or 4.1 please, which also installs the ElasticPress Plugin?

https://easyengine.io/tutorials/wordpress/elasticsearch-elasticpress/

**Comment by rahul286** [comment] 2018-05-11 08:17
Good idea. We are using elasticsearch on many sites. Although it shouldn't be a default, EE can make it easy to get going!

**Comment by eddr** [comment] 2018-05-16 11:12
That's a very nice feature and I'd like it very much too

**Comment by michacassola** [comment] 2018-05-28 18:00
@kirtangajjar Thanks for your input! I understand that you are busy with 4.0 and very much look forward to the next release both of 3.8.0 and 4.0! I even made a community topic that you guys did not comment in yet speaking about helping you to be able to prioritize EasyEngine more. Find it [here](https://community.rtcamp.com/t/sustainable-funding-for-easyengine-from-side-project-to-real-project/10605).
Please proceed in a pace that you see fit. I would still love to see this feature implemented though. But for the near 4.0 future I would love an updated do it yourselve tutorial with docker. (The one one easyengine.io seems very old).

@rahul286 I am happy that you agree! Easy is why I am here. 😃

**Comment by rahul286** [comment] 2018-08-03 13:33
Dupe of https://github.com/EasyEngine/easyengine/issues/542

**Closed by rahul286** 2018-08-03 13:33 UTC
Labels: kind/feature
